table measures_overview
	lineageTag: e8d77731-6bef-438b-8299-fe4c13187e95
	sourceLineageTag: [dbo].[measures_overview]

	measure 'Excess Inventory Rate' =
			DIVIDE(
			    CALCULATE(
			        COUNTROWS( gold_fact_item_site_setup ),
			        gold_fact_item_site_setup[maximum_level] > 0
			    ),
			    COUNTROWS( gold_fact_item_site_setup )
			)
		lineageTag: aaa2957a-8260-4174-86bf-6e4bf0b80975

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Reorder Frequency' =
			
			CALCULATE(
			    COUNTROWS( gold_fact_item_site_setup ),
			    gold_fact_item_site_setup[reorder_point] > 0
			)
		formatString: 0
		lineageTag: 8ce20bde-8a55-432a-9b03-edd939d75ae5

		changedProperty = Name

	measure 'Currency Fluctuation Impact' =
			
			VAR NormalizedValue = SUM( gold_fact_stock[Value_Unrestricted_GBP] )
			RETURN
			    IF( ISBLANK( NormalizedValue ), "Rate not available", NormalizedValue )
		formatString: £#,##0.00
		lineageTag: 0301e669-1a57-4873-93bb-dfb5aa3aa724

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Supplier Performance (Reversal Rate Proxy)' =
			
			VAR Reversals =
			    CALCULATE(
			        COUNTROWS( gold_fact_movements ),
			        gold_fact_movements[mt] IN { "312", "762" }
			    )
			VAR Receipts =
			    CALCULATE(
			        COUNTROWS( gold_fact_movements ),
			        gold_fact_movements[mt] = "311"
			    )
			RETURN
			    DIVIDE( Reversals, Receipts )
		formatString: 0
		lineageTag: e1eb285a-a368-47cb-8cc6-38ecb53ba448

		changedProperty = Name

	measure 'Currency Value Display ' =
			SWITCH(
			    SELECTEDVALUE( 'Currency Display'[Currency Display Order] ),
			    1, SUM( gold_fact_stock[Value_Unrestricted] ),
			    2, SUM( gold_fact_stock[Value_Unrestricted_GBP] ),
			    SUM( gold_fact_stock[Value_Unrestricted_GBP] )
			)
		formatString: #,##0.00
		lineageTag: 7d6894d6-196f-411f-bfa8-963ba4190c30

	measure 'test reorder' = MAX( gold_fact_item_site_setup[reorder_point] )
		lineageTag: 43684482-c5c4-4f40-804a-4d046d7f1697

	column id
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: a55874be-6b1a-48f9-9394-2c7040bffe67
		sourceLineageTag: id
		summarizeBy: sum
		sourceColumn: id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition measures_overview = entity
		mode: directLake
		source
			entityName: measures_overview
			expressionSource: 'DirectLake - lh_procurement_analytics'

